arguments:
  default_version: "2"
  default_level: "8"

paths:
  data_dir: "../data"
  pop_dir: "{data_dir}/population"
  final_data_dir : "final_data_source"
  voronoi_dir: "{data_dir}/voronoi_layers/v{version}/{buffer}"
  verification_dir: "{data_dir}/verification/v{version}/{buffer}"
  pop_tif_dir: "{data_dir}/population/unzipped"
  WWTP_tif_dir: "{data_dir}/WWTP_tifs"
  pop_output_dir: "{data_dir}/pop_voronoi_layers/v{version}/{buffer}"
  pop_dif_output_dir: "{data_dir}/pop_voronoi_layers/v{version}/{buffer}/diff"
  hw_plots_dir: "{data_dir}/verification/v{version}/{buffer}/plots/hw_plots"
  eu_plots_dir: "{data_dir}/verification/v{version}/{buffer}/plots/eu_plots"
  watersheds_zip_dir: "{data_dir}/hydrowaste_watersheds/{level}"
  dl_dir: "{data_dir}/DL_results"
  extra_points_dir: "extra_points"
  annotations_dir: "annotations"
  annotations_grid_dir: "{data_dir}/{annotations_dir}/GRID"
  annotations_by_osm_dir: "{data_dir}/{annotations_dir}/osm_by_idx"
  bboxes: "{data_dir}/bboxes.csv"
  cities: "{data_dir}/cities.csv"
  watershed: "{data_dir}/hydrobase_lvl8_combined.gpkg"
  rivershed: "{data_dir}/hydrorivers.gpkg"
  rivershed_output_path: "{data_dir}/hydroshed_basin_assigned.gpkg"
  overture: "{data_dir}/overture_maps_countries.parquet"
  hydrowaste: "{data_dir}/cleaned_hydrowaste.csv"
  dl_zipfile: "csvv2-2.zip"
  dl_mapfile: "aftersort.geojson"
  corrected_all: "{data_dir}/all_merged_v{version}.gpkg"
  new_points_filepath: "{data_dir}/new_locations_v{version}.gpkg"
  seg_corrected_south: "{data_dir}/seg_corrected_WWTP_enhanced_v{version}.gpkg"
  corrected_south: "{data_dir}/corrected_WWTP_enhanced_v{version}.geojson"
  eu_ref_filepath: "{data_dir}/{extra_points_dir}/UWWTD_TreatmentPlants.gpkg"
  canada_filepath: "{data_dir}/{extra_points_dir}/Canada_14_03_2025.csv"
  us_filepath: "{data_dir}/{extra_points_dir}/US_mapped_data_final.csv"
  germany_filepath: "{data_dir}/{extra_points_dir}/Germany_Hydra_waste_geospatial_corrected.geojson"
  osmgeo_filepath: "{data_dir}/wastewater_plant.geojson"
  paul_corrected_filepath: "{data_dir}/Enhanced_HW_WWTP__jun20_2025.geojson"

  seg_results_filepath: "/mnt/sds-hd/sd17f001/sukanya/wtp_seg/2026_global/Images_z17_512/results/csv/segoutput.csv"
 
  annotations_results_filepath: "/mnt/sds-hd/sd17f001/sukanya/wtp_seg/2026_global/annotated/mm/inference/csv_files/chunk_1/i2t_res1.csv"
  annotations_verf_image_outpath_dir: "/mnt/sds-hd/sd17f001/sukanya/wtp_seg/2026_global/annotated/mm/inference/test"
  annotated_images_output_dir:  "/mnt/sds-hd/sd17f001/sukanya/wtp_seg/2026_global/annotated/mm/Images_z17_512"
  annotations_images_dir: "/mnt/sds-hd/sd17f001/sukanya/wtp_seg/2026_global/mm/Images_z17_512" 
  annotations_temp_parquet_dir: "{data_dir}/temp_parquets"


  us_new_filepath: "{data_dir}/{final_data_dir}/final_USA_WWT_dec3.geojson"
  eu_new_filepath: "{data_dir}/{final_data_dir}/final_W_europe_WWT_dec3.geojson"
  thailand_filepath: "{data_dir}/{final_data_dir}/Thailand_500m_merged.geojson"
  csv_output_filepath: "{data_dir}/raster_country_stats.csv"
  non_served_outpath: "{data_dir}/non_served_areas.gpkg"
  non_served_above_threshold_outpath: "{data_dir}/non_served_areas_above_threshold.gpkg"
  non_served_nxt_river_outpath: "{data_dir}/non_served_nxt_river.gpkg"
  impact_pop_polygons_outpath: "{data_dir}/impact_pop_polygons.gpkg"
  industrial_areas_temp_db_path: "{data_dir}/temp_ingestion.duckdb"
  industrial_areas_ohsome_parquet_filepath: "{data_dir}/industrial_areas_final.parquet"
  pop_at_risk_output_filepath: "{data_dir}/pop_at_risk_pop.parquet"

  country_boundaries_filepath: "{data_dir}/boundaries/ne_110m_admin_0_countries.shp"
  interactive_piechart_html_filepath: "{data_dir}/figures/WWTP_type_interactive_piechart.html"
  static_piechart_filepath: "{data_dir}/figures/WWTP_type_piechart.png"
  leaflet_geojson_filepath: "{data_dir}/figures/leaflet_size.geojson"

s3:
  latest_url: "s3://overturemaps-us-west-2/release/2025-01-22.0"
  divisions: "{latest_url}/theme=divisions/type=division_area/*"

params:
  buffer: 15000
  max_workers: 16
  n_points: 250
  threshold: 500
  sigma: 3
  percent_threshold: 10
  percent_verification: 0.8
  osm_threshold: 1000
  eu_utm: 32634
  rad: 5000
  add_pop_max_workers: 8
  weight_method: square_root
  zoom_level: 8
  industrial_category_numbers: []
  
annotations:
  default_mode: array
  cell_size: 3072
  factor: 1.194
  max_workers: 8
  random_seed: 42
  overwrite: false

booleans:
  scipy: false
  cv2: false
  city_voronoi: false
  csv_files: false
  duckdb: false
  sindex_concurrency: true
  eu_correction: true
  remove_industrial: false

figures:
  pop_threshold: 1000
  approach: 3a

credentials:
 s3_access_key_id: "lymqeBSuT1dt9FhcUv3z"
 s3_secret_access_key: "XHZuA9NVJvG8hzfPnw2dkEcFlTBLy4s0trKx6WiU"
 url: "s3://heigit-ohsome-planet/data/v1/global/2026-03-09/contributions/latest/*.parquet"

execution:
 mode: "array"            # array | sequential | parallel

                         # Defaults: array (HPC), sequential (local)

                         # Leave empty for environment defaults

defaults:
  org_per_pop: 60.0
  width: 12.0
  c_limit: 5.0
  base_k: 0.23
  theta: 1.047
  step_m: 100.0
  least_discharge_cms: 0.269
  impact_radii: [1000, 2000]
